{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      {{- include "kobo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "kobo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      serviceAccountName: {{ include "kobo.serviceAccountName" . }}
      containers:
        - name: mongodb
          image: {{ printf "%s:%s" .Values.mongodb.image.repository .Values.mongodb.image.tag }}
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "kobo.fullname" . }}-kobo-env
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kobo.fullname" . }}-kobo-env
                  key: MONGO_ROOT_PASSWORD
          ports:
            - name: mongodb
              containerPort: 27017
          readinessProbe:
            tcpSocket:
              port: mongodb
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        {{- with .Values.mongodb.storageClass }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "kobo.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kobo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
{{- end }}