#!/usr/bin/env bash
set -euo pipefail
root=$(cd "$(dirname "$0")/.." && pwd)
mkdir -p "$root/runtime"/{config/nginx,config/enketo,logs/{kpi,nginx},static,media-mount/{kpi,kobocat},secrets/google}
set -a
source "${1:-$root/.env}"
[[ -f "$root/runtime/secrets/generated.env" ]] && source "$root/runtime/secrets/generated.env"
set +a
gen() { [[ "${!1:-}" != GENERATE && -n "${!1:-}" ]] || printf -v "$1" '%s' "$(openssl rand -hex 48)"; }
gen DJANGO_SECRET_KEY; gen ENKETO_API_KEY; gen ENKETO_ENCRYPTION_KEY; gen ENKETO_LESS_SECURE_ENCRYPTION_KEY; gen KOBO_SUPERUSER_PASSWORD
cat > "$root/runtime/secrets/generated.env" <<EOF
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
ENKETO_API_KEY=${ENKETO_API_KEY}
ENKETO_ENCRYPTION_KEY=${ENKETO_ENCRYPTION_KEY}
ENKETO_LESS_SECURE_ENCRYPTION_KEY=${ENKETO_LESS_SECURE_ENCRYPTION_KEY}
KOBO_SUPERUSER_PASSWORD=${KOBO_SUPERUSER_PASSWORD}
EOF
chmod 600 "$root/runtime/secrets/generated.env"
export POSTGRES_HOST=${POSTGRES_HOST:-cloud-sql-proxy} POSTGRES_PORT=${POSTGRES_PORT:-5432}
export MONGO_DB_URL REDIS_CACHE_PASSWORD REDIS_MAIN_PASSWORD
export REDIS_MAIN_URL=${REDIS_MAIN_URL:-redis://:${REDIS_MAIN_PASSWORD}@redis-main:6379/0}
redis_main_authority=${REDIS_MAIN_URL#*://}
redis_main_authority=${redis_main_authority#*@}
export ENKETO_REDIS_MAIN_HOST=${redis_main_authority%%:*}
redis_main_port_part=${redis_main_authority#*:}
export ENKETO_REDIS_MAIN_PORT=${redis_main_port_part%%/*}
[[ "$ENKETO_REDIS_MAIN_PORT" =~ ^[0-9]+$ ]] || export ENKETO_REDIS_MAIN_PORT=6379
postgres_password_urlencoded=$(python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1], safe=""))' "$POSTGRES_PASSWORD")
export KPI_DATABASE_URL="postgis://${POSTGRES_USER}:${postgres_password_urlencoded}@${POSTGRES_HOST}:${POSTGRES_PORT}/${KPI_POSTGRES_DB}"
export KC_DATABASE_URL="postgis://${POSTGRES_USER}:${postgres_password_urlencoded}@${POSTGRES_HOST}:${POSTGRES_PORT}/${KC_POSTGRES_DB}"
export DATABASE_URL="$KPI_DATABASE_URL" MONGO_DB_NAME
export PUBLIC_REQUEST_SCHEME PUBLIC_DOMAIN_NAME INTERNAL_DOMAIN_NAME
export KOBOFORM_PUBLIC_SUBDOMAIN KOBOCAT_PUBLIC_SUBDOMAIN ENKETO_PUBLIC_SUBDOMAIN
export KOBO_SUPERUSER_USERNAME DEFAULT_FROM_EMAIL="${DEFAULT_FROM_EMAIL:-admin@${PUBLIC_DOMAIN_NAME}}"
export DJANGO_DEBUG=0 USE_X_FORWARDED_HOST=True DJANGO_SESSION_COOKIE_AGE=604800
export CELERY_BROKER_URL=$(python3 -c 'import sys, urllib.parse; u=urllib.parse.urlsplit(sys.argv[1]); print(urllib.parse.urlunsplit((u.scheme, u.netloc, "/1", u.query, u.fragment)))' "$REDIS_MAIN_URL")
export REDIS_SESSION_URL="redis://:${REDIS_CACHE_PASSWORD}@redis-cache:6379/2"
export CACHE_URL="redis://:${REDIS_CACHE_PASSWORD}@redis-cache:6379/5"
export ENKETO_REDIS_CACHE_HOST=redis-cache ENKETO_REDIS_CACHE_PORT=6379
export ENKETO_PUBLIC_DOMAIN="${ENKETO_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}"
if [[ "${EXTERNAL_PROXY_ENABLED:-0}" == 0 ]]; then
  public_url_port=":${NGINX_BIND_PORT:-8080}"
  session_cookie_domain=''
else
  public_url_port=''
  session_cookie_domain=".${PUBLIC_DOMAIN_NAME}"
fi
cat > "$root/runtime/kobo.env" <<EOF
PUBLIC_REQUEST_SCHEME=${PUBLIC_REQUEST_SCHEME}
PUBLIC_DOMAIN_NAME=${PUBLIC_DOMAIN_NAME}
INTERNAL_DOMAIN_NAME=${INTERNAL_DOMAIN_NAME}
KOBOFORM_PUBLIC_SUBDOMAIN=${KOBOFORM_PUBLIC_SUBDOMAIN}
KOBOCAT_PUBLIC_SUBDOMAIN=${KOBOCAT_PUBLIC_SUBDOMAIN}
ENKETO_EXPRESS_PUBLIC_SUBDOMAIN=${ENKETO_PUBLIC_SUBDOMAIN}
DJANGO_DEBUG=0
TEMPLATE_DEBUG=0
USE_X_FORWARDED_HOST=True
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_SESSION_COOKIE_AGE=${DJANGO_SESSION_COOKIE_AGE}
DJANGO_ALLOWED_HOSTS=.${PUBLIC_DOMAIN_NAME} .${INTERNAL_DOMAIN_NAME}
SESSION_COOKIE_DOMAIN=${session_cookie_domain}
KPI_PREFIX=/
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
KPI_POSTGRES_DB=${KPI_POSTGRES_DB}
KC_POSTGRES_DB=${KC_POSTGRES_DB}
KPI_DATABASE_URL=${KPI_DATABASE_URL}
KC_DATABASE_URL=${KC_DATABASE_URL}
DATABASE_URL=${DATABASE_URL}
MONGO_DB_URL=${MONGO_DB_URL}
MONGO_DB_NAME=${MONGO_DB_NAME}
REDIS_PASSWORD=${REDIS_CACHE_PASSWORD}
REDIS_SESSION_URL=${REDIS_SESSION_URL}
CACHE_URL=${CACHE_URL}
CELERY_BROKER_URL=${CELERY_BROKER_URL}
ENKETO_API_KEY=${ENKETO_API_KEY}
ENKETO_REDIS_MAIN_URL=${REDIS_MAIN_URL}
KOBO_SUPERUSER_USERNAME=${KOBO_SUPERUSER_USERNAME}
KOBO_SUPERUSER_PASSWORD=${KOBO_SUPERUSER_PASSWORD}
CONSTANCE_SUPPORT_EMAIL=${DEFAULT_FROM_EMAIL}
DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
KOBOFORM_URL=${PUBLIC_REQUEST_SCHEME}://${KOBOFORM_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}${public_url_port}
KOBOFORM_INTERNAL_URL=http://${KOBOFORM_PUBLIC_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}
KOBOCAT_URL=${PUBLIC_REQUEST_SCHEME}://${KOBOCAT_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}${public_url_port}
KOBOCAT_INTERNAL_URL=http://${KOBOCAT_PUBLIC_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}
ENKETO_URL=${PUBLIC_REQUEST_SCHEME}://${ENKETO_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}${public_url_port}
ENKETO_INTERNAL_URL=http://${ENKETO_PUBLIC_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}
GCS_FUSE_ENABLED=${GCS_FUSE_ENABLED}
EOF
cat > "$root/runtime/enketo.env" <<EOF
NODE_ENV=production
REDIS_CACHE_HOST=redis-cache
REDIS_CACHE_PORT=6379
REDIS_CACHE_PASSWORD=${REDIS_CACHE_PASSWORD}
REDIS_MAIN_HOST=${ENKETO_REDIS_MAIN_HOST}
REDIS_MAIN_PORT=${ENKETO_REDIS_MAIN_PORT}
REDIS_MAIN_PASSWORD=${REDIS_MAIN_PASSWORD}
ENKETO_REDIS_MAIN_URL=${REDIS_MAIN_URL}
ENKETO_REDIS_CACHE_URL=${REDIS_SESSION_URL%/2}/0
EOF
sed \
  -e "s|__INTERNAL_API_PORT__|${NGINX_INTERNAL_API_PORT:-8080}|g" \
  -e "s|__KPI_INTERNAL__|${KOBOFORM_PUBLIC_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}|g" \
  -e "s|__KC_INTERNAL__|${KOBOCAT_PUBLIC_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}|g" \
  -e "s|__EE_INTERNAL__|${ENKETO_PUBLIC_SUBDOMAIN}.${INTERNAL_DOMAIN_NAME}|g" \
  -e "s|__KPI__|${KOBOFORM_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}|g" \
  -e "s|__KC__|${KOBOCAT_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}|g" \
  -e "s|__EE__|${ENKETO_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}|g" \
  "$root/config/nginx/nginx.conf.tpl" > "$root/runtime/config/nginx/nginx.conf"
sed -e "s|__API_KEY__|${ENKETO_API_KEY}|g" -e "s|__ENCRYPTION_KEY__|${ENKETO_ENCRYPTION_KEY}|g" -e "s|__LESS_SECURE_ENCRYPTION_KEY__|${ENKETO_LESS_SECURE_ENCRYPTION_KEY}|g" -e "s|__SUPPORT_EMAIL__|${DEFAULT_FROM_EMAIL}|g" -e "s|__CACHE_PASSWORD__|${REDIS_CACHE_PASSWORD}|g" -e "s|__MAIN_HOST__|${ENKETO_REDIS_MAIN_HOST}|g" -e "s|__MAIN_PORT__|${ENKETO_REDIS_MAIN_PORT}|g" -e "s|__MAIN_PASSWORD__|${REDIS_MAIN_PASSWORD}|g" "$root/config/enketo/config.json.tpl" > "$root/runtime/config/enketo/config.json"
chmod 600 "$root/runtime/kobo.env" "$root/runtime/enketo.env"
printf 'Rendered runtime configuration under %s/runtime\n' "$root"
